name: Make Docs AFter Merging Pull Request

on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python  3.7
        uses: actions/setup-python@v3
        with:
          python-version:  3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip urubu
          python -m pip install markdown==2.6.11
      - name: Running Make
        run: |
          make
