name: Make Docs AFter Merging Pull Request

on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Running Make
        run: |
          make
